name: client
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  args: ^2.5.0  
  sqlite3: ^1.4.0
  path: ^1.8.0
  http: ^1.2.2
  json_annotation: ^4.8.0
  json_serializable: ^6.7.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
